### ISSUE TITLE
create a frameset with 2 rows and 2 columns , clicking the button in a frame should make changes in the another frame

### ISSUE THREAD

**Issue by godwin-l** [Jacob-h-michael/html#3]

**Comment by Jacob-h-michael** [comment]
sry i dont know i can create tables with 2 rows and column and visualize button dont to know to make changes in the nxt frame with the click in the button and frameset tag is unavailable for html 5

**Comment by godwin-l** [comment]
https://www.tutorialspoint.com/html/html_frames.htm

here there are some examples which would help you

**Comment by godwin-l** [comment]
check this and try , if still you are confused tell me

**Comment by godwin-l** [comment]
```


<FRAMESET rows="50%,50%">
  <FRAMESET cols="50%,50%">
      <FRAME src="frame1">
      <FRAME src="frame2">
  </FRAMESET>
  <FRAMESET cols="50%,50%">
  <FRAME src="frame3">
  <FRAME src="frame4">
  </FRAMESET>
</FRAMESET>

```

**Comment by godwin-l** [comment]
Sample Example:

main.html

```
<frameset cols="50%,50%">
    <frame src="frame1.html" name="frame1">
        <frame src="frame2.html" name="frame2">
</frameset>
```

frame1.html

`<a href="https://cliq.zoho.in/index.do" target="frame2">Cliq</a>`

frame2.html

`<h1>Cliq website will be displayed here on clicking cliq link on your left</h1>`


add these three files in a folder and run main.html
