### ISSUE TITLE
create div as per in screen shots

### ISSUE THREAD

**Issue by godwin-l** [Jacob-h-michael/html#9]
1)
![images (2)](https://user-images.githubusercontent.com/34455677/82366293-a0cab100-9a2f-11ea-9c52-3ce475dd9de0.png)

2)
![tQCp5](https://user-images.githubusercontent.com/34455677/82366302-a1fbde00-9a2f-11ea-9f99-77f9f33cabb8.png)

3)
![images (1)](https://user-images.githubusercontent.com/34455677/82366305-a32d0b00-9a2f-11ea-886f-c803156c6624.png)

**Comment by godwin-l** [comment]
2) 

Try this da

```
<html>

<head>
    <style>
        .test {
            display: inline-block;
        }
    </style>
</head>

<body>
    <div>
        <div class="test" style="height:60%;background-color:red;width:40%"></div>
        <div class="test" style="height:20%;background-color:green;width:59%;margin-bottom: 375px;"></div>


        <div class="test" style="height: 40%;background-color: pink;width: 33.59%;margin-left: 742px;margin-top: -377px;/* float:right; */z-index: 10;"></div>
        <div class="test" style="height: 40%;background-color: blue;width: 25%;margin-left: 1365px;margin-top: -377px;/* float:right; */z-index: 10;"></div>
    </div>
</body>

</html>
```

**Comment by godwin-l** [comment]
![Screenshot from 2020-05-22 15-35-43](https://user-images.githubusercontent.com/34455677/82656793-ee1e6c80-9c41-11ea-947c-8cf0d82518fb.png)

**Comment by Jacob-h-michael** [comment]
``

**Comment by Jacob-h-michael** [comment]
![Untitled](https://user-images.githubusercontent.com/65463216/82657482-080c7f00-9c43-11ea-8a56-7fa3295d3f61.png)

**Comment by Jacob-h-michael** [comment]
2. what mistake ihave done none is displaying
<html>

<head>
    <style>
        .test {
            display: inline-block;
        }
    </style>
</head>

<body>
    <div class="test" style="background-color: cadetblue" width: 50% height:50%>


    </div>
    <div class="test" style="background-color:red  float: left" width:50% height:50%></div>
    <div class="test" style="background-color:yellowgreen" width:100% height:50%></div>

</body>

</html>

**Comment by godwin-l** [comment]
You missed to use semi-colon (;) between the style attributes in div tag and height,width were out of the quotes ,

I have given the correct syntax below:

```
<style> .test { display: inline-block; } </style>
<div class="test" style="background-color:red;float:left;width:50%;height:50%"></div>
<div class="test" style="background-color:yellow;width:100%;height:50%"></div>
```

**Comment by godwin-l** [comment]
One Last Time to say good bye to div


![download (10)](https://user-images.githubusercontent.com/34455677/82702049-dd481800-9c8e-11ea-93ce-f547a3a68ae5.png)


the gaps between la div is not needed

**Comment by Jacob-h-michael** [comment]
no blocks are displaying. semicolon coln are perfect
<!DOCTYPE html>
<html>

<head>
    <style>
        .test {
            display: inline-block;
        }
    </style>
</head>

<body>
    <div class="test" style="background-color:brown;width:25%;height:60%; float:left;"></div>
    <div class="test" style="background-color:green;width:35%;height:60%; float: left;"></div>
    <div class="test" style="background-color:yellowgreen;width:20%;height:100%; float:left;"></div>
    <div class="test" style="background-color:violet;width:20%;height:80%; float:left;"></div>
    <div class="test" style="background-color:bisque;width:20%;height:40%; float:left;"></div>
    <div class="test" style="background-color:pink;width:40%;height:60%; float:left;"></div>
    <div class="test" style="background-color:khaki;width:20%;height:20%; float:left;"></div>
    <div class="test" style="background-color:wheat;width:20%;height:20%; float:left;"></div>

</body>

</html>

**Comment by godwin-l** [comment]
can you share me the HTML part @Jacob-h-michael  ?

**Comment by Jacob-h-michael** [comment]
<!DOCTYPE html>
<html>

<head>
    <style>
        .test {
            display: inline-block;
        }
    </style>
</head>

<body>
    <div class="test" style="background-color:brown;width:25%;height:60%; float:left;"></div>
    <div class="test" style="background-color:green;width:35%;height:60%; float: left;"></div>
    <div class="test" style="background-color:yellowgreen;width:20%;height:100%; float:left;"></div>
    <div class="test" style="background-color:violet;width:20%;height:80%; float:left;"></div>
    <div class="test" style="background-color:bisque;width:20%;height:40%; float:left;"></div>
    <div class="test" style="background-color:pink;width:40%;height:60%; float:left;"></div>
    <div class="test" style="background-color:khaki;width:20%;height:20%; float:left;"></div>
    <div class="test" style="background-color:wheat;width:20%;height:20%; float:left;"></div>

</body>

</html>

**Comment by Jacob-h-michael** [comment]
`<!DOCTYPE html>
<html>

<head>
    <style>
        .test {
            display: inline-block;
        }
    </style>
</head>

<body>
    <div class="test" style="background-color:brown;width:25%;height:60%; float:left;"></div>
    <div class="test" style="background-color:green;width:35%;height:60%; float: left;"></div>
    <div class="test" style="background-color:yellowgreen;width:20%;height:100%; float:left;"></div>
    <div class="test" style="background-color:violet;width:20%;height:80%; float:left;"></div>
    <div class="test" style="background-color:bisque;width:20%;height:40%; float:left;"></div>
    <div class="test" style="background-color:pink;width:40%;height:60%; float:left;"></div>
    <div class="test" style="background-color:khaki;width:20%;height:20%; float:left;"></div>
    <div class="test" style="background-color:wheat;width:20%;height:20%; float:left;"></div>

</body>

</html>`

**Comment by Jacob-h-michael** [comment]
<!DOCTYPE html>
<html>

<head>
    <style>
        .test {
            display: inline-block;
        }
    </style>
</head>

<body>
    <div class="test" style="background-color:brown;width:25%;height:60%; float:left;"></div>
    <div class="test" style="background-color:green;width:35%;height:60%; float: left;"></div>
    <div class="test" style="background-color:yellowgreen;width:20%;height:100%; float:left;"></div>
    <div class="test" style="background-color:violet;width:20%;height:80%; float:left;"></div>
    <div class="test" style="background-color:bisque;width:20%;height:40%; float:left;"></div>
    <div class="test" style="background-color:pink;width:40%;height:60%; float:left;"></div>
    <div class="test" style="background-color:khaki;width:20%;height:20%; float:left;"></div>
    <div class="test" style="background-color:wheat;width:20%;height:20%; float:left;"></div>

</body>

</html>``

**Comment by Jacob-h-michael** [comment]
```
<!DOCTYPE html>
<html>

<head>
    <style>
        .test {
            display: inline-block;
        }
    </style>
</head>

<body>
    <div class="test" style="background-color:brown;width:25%;height:60%; float:left;"></div>
    <div class="test" style="background-color:green;width:35%;height:60%; float: left;"></div>
    <div class="test" style="background-color:yellowgreen;width:20%;height:100%; float:left;"></div>
    <div class="test" style="background-color:violet;width:20%;height:80%; float:left;"></div>
    <div class="test" style="background-color:bisque;width:20%;height:40%; float:left;"></div>
    <div class="test" style="background-color:pink;width:40%;height:60%; float:left;"></div>
    <div class="test" style="background-color:khaki;width:20%;height:20%; float:left;"></div>
    <div class="test" style="background-color:wheat;width:20%;height:20%; float:left;"></div>

</body>

</html>
```

**Comment by godwin-l** [comment]
remove `<!DOCTYPE html>` and check

**Comment by godwin-l** [comment]
this is the latest format of doc type :

`<!DOCTYPE html->`

a hiphen will be at the end of html

this would be working

**Comment by Jacob-h-michael** [comment]
```
<!DOCTYPE html->
<html>

<head>
    <style>
        .test {
            display: inline-block;
        }
    </style>
</head>

<body>
    <div class="test" style="background-color:brown;width:25%;height:60%; float:left;"></div>

    <div class="test" style="background-color:green;width:35%;height:60%; float: left;"></div>
    <div class="test" style="background-color:yellowgreen;width:20%;height:100%; float:left;"></div>
    <div class="test" style="background-color:violet;width:20%;height:80%; float:left;"></div>
    <div class="test" style="background-color:khaki;width:20%;height:20%; float:left;"></div>
    <div class="test" style="background-color:bisque;width:21%;height:20%;"></div>


    <div class="test" style="background-color:pink;width:38%;height:40%; "></div>
    <div class="test" style="background-color:blue;width:20%;height:20%; "></div>






</body>

</html>
```

**Comment by Jacob-h-michael** [comment]
![Untitled](https://user-images.githubusercontent.com/65463216/82729147-df53ba80-9d12-11ea-9904-705d4bbffa0b.png)

**Comment by Jacob-h-michael** [comment]
![Untitled](https://user-images.githubusercontent.com/65463216/82729181-0ca06880-9d13-11ea-88eb-c44e88206dd0.png)

**Comment by godwin-l** [comment]
make use of margins

**Comment by godwin-l** [comment]
https://www.w3schools.com/css/css_margin.asp

**Comment by Jacob-h-michael** [comment]
`<!DOCTYPE html>
<html>

<body>
    <div style="background-color:rosybrown;height: 69px;">
        <div style="display: block;width: 50px;background-color:black;opacity: 1;position: absolute;"></div>
        <div style="display: block;width: 60px;background-color:rgb(255, 166, 0);position: absolute;"></div>


    </div>
</body>

</html>`

**Comment by Jacob-h-michael** [comment]
```
<!DOCTYPE html>
<html>

<body>
    <div style="background-color:rosybrown;height: 69px;">
        <div style="display: block;width: 50px;background-color:black;opacity: 1;position: absolute;"></div>
        <div style="display: block;width: 60px;background-color:rgb(255, 166, 0);position: absolute;"></div>


    </div>
</body>

</html>``
```

**Comment by godwin-l** [comment]
```
<html><head></head><body>
    <div style="background-color:rosybrown;height: 69px;">
        <div style="display: block;width: 50px;background-color:black;">&nbsp;</div>
        <div style="display: block;width: 60px;background-color:rgb(255, 166, 0);">&nbsp;</div>

    </div>
</body></html>
```

**Comment by godwin-l** [comment]
adding nbsp between the div solves the issue
